server:
      port: 8081
      servlet.context-path: /demo

test:
    data1: 测试数1
    data2: 测试数2

content: "data1: ${test.data1}, data2: ${test.data2}}"

man:
  prop1: a
  prop2: b
  prop3: c
  prop4: d
  prop5: e
